---

- name: add nodesource keys
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: install nodesource v4 repos
  apt_repository: repo="deb https://deb.nodesource.com/node_4.x jessie main"
  with_items:
    - "deb https://deb.nodesource.com/node_4.x jessie main"
    - "deb-src https://deb.nodesource.com/node_4.x jessie main"
  notify: update apt cache
