---

- name: install homebridge dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - libavahi-compat-libdnssd-dev
    - git

- name: install homebridge via {{ nodejs_bindir }}/npm
  become: yes
  npm:
    global: yes
    name: homebridge
    executable: "{{ nodejs_bindir}}/npm"
  environment:
    PATH: "{{ nodejs_bindir}}:{{ ansible_env.PATH }}"

- name: add homebridge user
  become: yes
  user:
    name: homebridge
    home: "{{ homebridge_dir }}"
    createhome: yes
    comment: "HomeBridge"

- name: add systemd unit and EnvFile
  become: yes
  template:
    src: ".{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - "{{ homebridge_defaults }}"
    - /etc/systemd/system/homebridge.service
  notify: bounce homebridge

- name: start homebridge
  become: yes
  service:
    name: homebridge
    state: started
    enabled: yes
